
build: joc.cpp noteImproved.cpp
	g++ joc.cpp -o joc
	g++ noteImproved.cpp -o note
	g++ -std=c++0x cablare.cpp -o cablare

run-p1: joc
	./joc
run-p2: note
	./note
run-p3: cablare
	./cablare
	
clean: 
	rm joc cablare note
